[build]
  publish = "public"
  command = "npm run build"
  
[[redirects]]
  from = "/*"
  to = "/error/index.html"
  status = 404
  
[[redirects]]
  from = "/projects/mothers-day"
  to = "/projects/dear-mom"
  status = 301